### ISSUE TITLE
Attribution

### ISSUE THREAD

**Issue by diced** [AlphaNecron/Chakram#11]
It has been brought to my attention that many parts of this codebase seem to be exact copies or similar to https://github.com/diced/zipline. While this may be okay when done under a fork, what's being done here is not exactly correct. Whenever there are updates to Zipline it seems that they are also comitted here, with no attribution to Zipline. This is a warning and any further action will be taken if this isn't made as a fork. I'm open to discussion if you would like to talk things out.

Here are some files that resemble a near 100% copy. The first column is Zipline and the last is Void.
```
zipline/Dockerfile Void/Dockerfile
zipline/.dockerignore Void/.dockerignore
zipline/.husky/commit-msg Void/.husky/commit-msg
zipline/LICENSE Void/LICENSE
zipline/next-env.d.ts Void/next-env.d.ts
zipline/package.json Void/package.json
zipline/prisma/migrations/20210827202147_favorite/migration.sql Void/prisma/migrations/20210926091433_url_shortener/migration.sql
zipline/prisma/migrations/20210901024501_embed_image/migration.sql Void/prisma/migrations/20210926091433_url_shortener/migration.sql
zipline/prisma/migrations/20210925030428_vanity_url/migration.sql Void/prisma/migrations/20210926091433_url_shortener/migration.sql
zipline/prisma/migrations/20211003022626_site_name/migration.sql Void/prisma/migrations/20210926091433_url_shortener/migration.sql
zipline/prisma/migrations/migration_lock.toml Void/prisma/migrations/migration_lock.toml
zipline/src/lib/hooks/useFetch.ts Void/src/lib/hooks/useFetch.ts
zipline/src/lib/prisma.ts Void/src/lib/prisma.ts
zipline/src/lib/redux/reducers.ts Void/src/lib/redux/reducers.ts
zipline/src/lib/redux/reducers/user.ts Void/src/lib/redux/reducers/user.ts
zipline/src/lib/redux/store.ts Void/src/lib/redux/store.ts
zipline/yarn.lock Void/yarn.lock
```
*There are many other files that also have copies yet they won't be picked up as the frontend was changed.*

**Comment by AlphaNecron** [comment]
Yes, this is basically a redesigned version of Zipline with a Discord bot.

**Comment by AlphaNecron** [comment]
Btw i copied the API and created Void with `create-next-app` so it's easier to do stuff. Sorry for not leaving the credit.

**Comment by AlphaNecron** [comment]
Updated the README, i will close this issue, sorry once again!
