### ISSUE TITLE
I'm getting this error and my images don't work

### ISSUE THREAD

**Issue by RehanPlayz** [AlphaNecron/Chakram#13]
https://i.rehanplayz.gq/kvci9w4xi0a.jpg

**Comment by RehanPlayz** [comment]
@AlphaNecron

**Comment by AlphaNecron** [comment]
Try disabling Hotlink protection.
[Thread](https://community.cloudflare.com/t/hotlink-protection-question/80163)

**Comment by RehanPlayz** [comment]
> Try disabling Hotlink protection. [Thread](https://community.cloudflare.com/t/hotlink-protection-question/80163)

Done

**Comment by AlphaNecron** [comment]
Fixed?

**Comment by RehanPlayz** [comment]
> Fixed?

Nope

**Comment by RehanPlayz** [comment]
> https://i.rehanplayz.gq/kvci9w4xi0a.jpg

This is using a different image host

**Comment by AlphaNecron** [comment]
Just ignore it, that happens when you don't enable logging in Discord.

**Comment by RehanPlayz** [comment]
> Just ignore it, that happens when you don't enable logging in Discord.

How do I enable it and wdym ignore the images don't work lol (I don't even get the link copied to the clipboard)

**Comment by AlphaNecron** [comment]
> > Just ignore it, that happens when you don't enable logging in Discord.
> 
> How do I enable it and wdym ignore the images don't work lol (I don't even get the link copied to the clipboard)

Edit `config.toml`.

**Comment by RehanPlayz** [comment]
> > > Just ignore it, that happens when you don't enable logging in Discord.
> > 
> > 
> > How do I enable it and wdym ignore the images don't work lol (I don't even get the link copied to the clipboard)
> 
> Edit `config.toml`.

What exactly should do and will my images will work then?

**Comment by AlphaNecron** [comment]
> What exactly should do and will my images will work then?

```toml
[bot]
enabled = true
prefix = '&'
token = 'your_bot_token'
admin = ['your_discord_id']
log_channel = 'your_channel_to_log'
default_uid = 1
hostname = 'your_domain'
```
