### ISSUE TITLE
bytes.toFixed is not a function

### ISSUE THREAD

**Issue by bartoszewski54** [AlphaNecron/Chakram#15]
Hi!
Recently i've setup Void on my VPS, and im having an issue that randomly appears when uploading any type of file.
Im using docker-compose version.
<img width="486" alt="fd55205375 1" src="https://user-images.githubusercontent.com/62442295/140655952-eb84f129-e535-4607-b0a5-822d3ea79885.png">

And website is returning this type of error:
https://i.bartoszewski.xyz/58f8a9e287.png
Example URL with this error: 
https://bartoszewski.solutions/%E2%80%8D%E2%80%8C%E2%80%8B%E2%80%8C%E2%80%8C%E2%80%8D
It's really weird and i have no idea why it's happenning, since it doesn't appear everytime someone uploads a file, but it happens quite often.

**Comment by AlphaNecron** [comment]
Will fix this issue later, currently having an online class. Sorry.

**Comment by AlphaNecron** [comment]
Try again using `dev` image and see.

**Comment by bartoszewski54** [comment]
Alright, will try. Thanks for help!
