### ISSUE TITLE
Adding Domain with Nginx breaks stuff

### ISSUE THREAD

**Issue by Atomoyo** [AlphaNecron/Chakram#19]
### **Major Issues**
When you add a nginx server to add a domain, lots of stuff breaks such as the embeds in discord and the viewer when you go to {ipaddress}.com/{firename}.

_**Picture Viewer**_
Such as the viewer is the photo below.
![7IilOl](https://user-images.githubusercontent.com/72045911/152025598-265c7ee1-412c-4698-8205-11eb9e5bea81.png)
So I have changed values to redirect to domain.com/r/{filename.extension} which means the pictures show up like this
![chrome_VpBgJUaW9h](https://user-images.githubusercontent.com/72045911/152027145-795217e9-6cb8-4617-89e5-ec9e24c11786.png)

This comes up when requesting domain.com/{firename}.
`FetchError: request to http://domain.extension/r/WvutuQ.png failed, reason: connect ECONNREFUSED {ipaddress}:80
    at ClientRequest.<anonymous> (/root/Void/node_modules/node-fetch/lib/index.js:1491:11)
    at ClientRequest.emit (node:events:390:28)
    at ClientRequest.emit (node:domain:475:12)
    at Socket.socketErrorListener (node:_http_client:447:9)
    at Socket.emit (node:events:390:28)
    at Socket.emit (node:domain:475:12)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  type: 'system',
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED'
}
`
I think it has to do with the js file trying to fetch from http but I'm not sure how to fix that

_**Broken Embeds**_
The top is with the domain the bottom is with the url of the VPS
![Discord_adZz1l1qt9](https://user-images.githubusercontent.com/72045911/152026586-5ee8d2f1-d1f0-44f1-aedb-fc613468e25b.png)

_**Blocked File Types**_
Regardless of the domain I can upload exe's despite them being blocked in the config file

_**File Upload Limiter**_
Regardless of the domain I can upload files of any size despite them being blocked in the config file

I appreciate that this is all free work etc.

If I could get help to fix these I would be happy to donate to the author if you are accepting because the rest of the source is all working and is pretty nice.

Besides that everything else seemed to have worked, I had to change the discord bot to use the /r/{filename.extension} so the pictures show up in the embeds

**Comment by AlphaNecron** [comment]
Mine works fine lol, check your cert maybe?

**Comment by AlphaNecron** [comment]
Btw blocked filetypes does'nt work for admins.

**Comment by AlphaNecron** [comment]
So does size limiting.

**Comment by AlphaNecron** [comment]
Did you enable `secure` in your config.toml?

**Comment by AlphaNecron** [comment]
I believe enabling `secure` will solve your first issue.

**Comment by Atomoyo** [comment]
Ahh yeah that fixed it, I set the server up while I was waiting for the SSL cert to verify so I forgot to toggle that on. The file blocking and size limiting works too, now that I think of it, it makes sense to allow Admins to bypass it. 

Got a donation page? You can message me on discord Atomoyo#6969 about it

**Comment by AlphaNecron** [comment]
I don't have PayPal, only Visa lol

**Comment by Atomoyo** [comment]
I’ll message you on discord rather than here.
