### ISSUE TITLE
Can you add 'latest' tag for Docker images?

### ISSUE THREAD

**Issue by SmartPhoneLover** [AlphaNecron/Chakram#20]
Hello, first of all, congrats for your work. Love it! Perfect design.

Now, as mentioned in the title, I would like to know if you can add the 'latest' tag for future releases. I think, it will make easier the installation. Currently, the latest one is 'v0'.

So, with 'alphanecron/void:latest' would pull the latest version automatically.

Thank you.

**Comment by AlphaNecron** [comment]
`v0` is the latest tag.

**Comment by AlphaNecron** [comment]
Or if you want a persistent tag, use `dev`.

**Comment by SmartPhoneLover** [comment]
Ohh, perfect. Thank you for the quick reply.
