### ISSUE TITLE
Make thumbnails larger also txt files do not show in thumb view

### ISSUE THREAD

**Issue by ItsNoted** [AlphaNecron/Chakram#28]
Perhaps less thumbnails in a row to have larger thumbnails would be nice.

Also, txt files do not show in thumb view. Maybe make it so they do and just use a generic note icon. and any other file that is not a photo or video, just use a generic icon for thumb view. That would be ideal.

I am really liking this project. Well done!

![111111](https://user-images.githubusercontent.com/57927413/167951837-cf9b1a2f-e52f-452f-be08-f5e961a48df1.png)

**Comment by AlphaNecron** [comment]
v0 is going to be discontinued, stay tuned for v1 this summer.

**Comment by AlphaNecron** [comment]
Like this?
![Void](https://user-images.githubusercontent.com/57827456/162430720-6c92f257-1813-4677-8c33-d02bae9d445e.png)
This is what I've been working all the time.

**Comment by ItsNoted** [comment]
> Like this?
> ![Void](https://user-images.githubusercontent.com/57827456/162430720-6c92f257-1813-4677-8c33-d02bae9d445e.png)
> This is what I've been working all the time.

Yes! Very good. Thanks for the update 😍

**Comment by AlphaNecron** [comment]
Currently practicing for the provincial programming contest, so I literally have no time for Void. I might have free time to develop Void starting from June.

**Comment by AlphaNecron** [comment]
Gonna close this issue now. Thanks for paying attention to `Void` 😉.

**Comment by ItsNoted** [comment]
Is this new one similar to Zipline? https://github.com/diced/zipline why do these looks so similar.

**Comment by AlphaNecron** [comment]
This project was initially based on Zipline. Some of the source code written nowadays are taken from Zipline.

**Comment by ItsNoted** [comment]
Good! When you decide to rewrite it will you consider putting the newest thumbnails at the top rather than the bottom?

**Comment by AlphaNecron** [comment]
What do you mean?

**Comment by ItsNoted** [comment]
> What do you mean?

Currently when I take a new screenshot with sharex, all of the new thumbnails show up at the bottom of the thumbnail viewer in the web panel. So I have to scroll all the way down to see the newest uploads.

**Comment by AlphaNecron** [comment]
Sure.
