### ISSUE TITLE
Making a new user without making them an Administrator

### ISSUE THREAD

**Issue by Lunascaped** [AlphaNecron/Chakram#30]
I want to give someone access to use my Void instance as a screenshot service with ShareX, however I don't want them to be able to delete my account. How do I accomplish this? The site says that ticking the administrator box is required.

**Comment by Secr3ts** [comment]
same lol

**Comment by AlphaNecron** [comment]
Try the latest commit [`f999155`](https://github.com/AlphaNecron/Void/commit/f99915506afaaeb3c3d4ec6d3f682d23c3735677) in the dev branch.
