### ISSUE TITLE
Error while uploading the file

### ISSUE THREAD

**Issue by Ryan0204** [AlphaNecron/Chakram#33]
JSON.parse: unexpected character at line 1 column 1 of the JSON data

I am uploading .mp4 file which is 158MB and i got this error.

**Comment by AlphaNecron** [comment]
Can you send the logs here?

**Comment by Ryan0204** [comment]
May i know how can i get the log? Console don't have any error message

**Comment by AlphaNecron** [comment]
> May i know how can i get the log? Console don't have any error message

There should be, are you using Docker?

**Comment by Ryan0204** [comment]
Nope.  I use yarn. And host in pterodactyl panel.

**Comment by AlphaNecron** [comment]
It's hard to do anything without logs. Try finding the logs.

**Comment by Ryan0204** [comment]
Sorry but there is **NO** any log. I can only provide you video info.

Size: 165.5MB
Kind: MPEG-4 Movie

**Comment by AlphaNecron** [comment]
Try a file under 100MB?

**Comment by AlphaNecron** [comment]
Can you use plain Node to run Void?

**Comment by Ryan0204** [comment]
> 

File under 100MB will work

**Comment by Ryan0204** [comment]
btw one more suggestion is support paste image to upload like imgur

**Comment by AlphaNecron** [comment]
Sure, it will be included in the next major update, along with upload estimation and cancellation.

**Comment by AlphaNecron** [comment]
If you are using `nginx` with the config in the README, try increasing the max body size.
