### ISSUE TITLE
Wont start v1

### ISSUE THREAD

**Issue by Jamior** [AlphaNecron/Chakram#40]
[23:51:38] Void ›	ℹ info Reading config file
[23:51:38] Void ›	✖ error Cannot read properties of undefined (reading 'outputDirectory')
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by AlphaNecron** [comment]
Do not try `v1` now, its experimental. I pushed it to GitHub just for backup purpose.

**Comment by Jamior** [comment]
Is there an eta on the v1?

**Comment by AlphaNecron** [comment]
This year probably, stay tuned.
