### ISSUE TITLE
Files taking a very long time to upload suddenly.

### ISSUE THREAD

**Issue by Lunascaped** [AlphaNecron/Chakram#43]
I've passed around 550 files uploaded in my Void instance and now whenever I upload something using ShareX (and only ShareX), everything takes like 3 times long to upload. A minute and a half will pass before each upload, it works fine in the web client. I'm not sure if this is a ShareX issue but I don't have this issue with anything other than my Void config. I should also say this isn't always consistent, sometimes it works as normal and sometimes it doesn't. I see nothing in my logs that is abnormal.

**Comment by AlphaNecron** [comment]
Try downgrading ShareX? Maybe the latest version degraded the performance.

**Comment by Lunascaped** [comment]
> Try downgrading ShareX? Maybe the latest version degraded the performance.

Downgraded back to 13.7 (where i know it worked flawlessly) and issue persists.

**Comment by AlphaNecron** [comment]
Idk, if the web client works fine then ShareX should be either?

**Comment by Lunascaped** [comment]
That's what I think too since its the same API, would cloudflare have anything to do with it maybe?

**Comment by AlphaNecron** [comment]
Try turning off Cloudflare and compare?

**Comment by Lunascaped** [comment]
Going to my local server on my network directly seems to work perfectly fine, but I don't see any logs in my cloudflare about it attempting to block anything. It's just really slow.

**Comment by Lunascaped** [comment]
![image](https://user-images.githubusercontent.com/21148758/187111214-fa5979f0-7e79-4a4b-8ea3-f39ba4f86a23.png)
I still cannot fathom why it would make such a dramatic increase, it was working fine 2 days ago.

**Comment by AlphaNecron** [comment]
Try uploading via Postman? If it works then thats ShareX's fault.

**Comment by Lunascaped** [comment]
Closed due to it suddenly fixing itself
