### ISSUE TITLE
yarn build error

### ISSUE THREAD

**Issue by vincethepro** [AlphaNecron/Chakram#44]
Got this when I ran yarn build - i had to shrink it
-----------------------------------
100:24  Error: Expected linebreaks to be 'LF' but found 'CRLF'.  linebreak-style
101:21  Error: Expected linebreaks to be 'LF' but found 'CRLF'.  linebreak-style
102:30  Error: Expected linebreaks to be 'LF' but found 'CRLF'.  linebreak-style
103:42  Error: Expected linebreaks to be 'LF' but found 'CRLF'.  linebreak-style
104:44  Error: Expected linebreaks to be 'LF' but found 'CRLF'.  linebreak-style
105:112  Error: Expected linebreaks to be 'LF' but found 'CRLF'.  linebreak-style
106:75  Error: Expected linebreaks to be 'LF' but found 'CRLF'.  linebreak-style
107:99  Error: Expected linebreaks to be 'LF' but found 'CRLF'.  linebreak-style
108:84  Error: Expected linebreaks to be 'LF' but found 'CRLF'.  linebreak-style
109:37  Error: Expected linebreaks to be 'LF' but found 'CRLF'.  linebreak-style
110:23  Error: Expected linebreaks to be 'LF' but found 'CRLF'.  linebreak-style
111:27  Error: Expected linebreaks to be 'LF' but found 'CRLF'.  linebreak-style
112:42  Error: Expected linebreaks to be 'LF' but found 'CRLF'.  linebreak-style
113:44  Error: Expected linebreaks to be 'LF' but found 'CRLF'.  linebreak-style
114:105  Error: Expected linebreaks to be 'LF' but found 'CRLF'.  linebreak-style
115:75  Error: Expected linebreaks to be 'LF' but found 'CRLF'.  linebreak-style
116:94  Error: Expected linebreaks to be 'LF' but found 'CRLF'.  linebreak-style
117:37  Error: Expected linebreaks to be 'LF' but found 'CRLF'.  linebreak-style
118:23  Error: Expected linebreaks to be 'LF' but found 'CRLF'.  linebreak-style
119:27  Error: Expected linebreaks to be 'LF' but found 'CRLF'.  linebreak-style
120:57  Error: Expected linebreaks to be 'LF' but found 'CRLF'.  linebreak-style
121:38  Error: Expected linebreaks to be 'LF' but found 'CRLF'.  linebreak-style
122:36  Error: Expected linebreaks to be 'LF' but found 'CRLF'.  linebreak-style
123:79  Error: Expected linebreaks to be 'LF' but found 'CRLF'.  linebreak-style
124:47  Error: Expected linebreaks to be 'LF' but found 'CRLF'.  linebreak-style
125:37  Error: Expected linebreaks to be 'LF' but found 'CRLF'.  linebreak-style
126:23  Error: Expected linebreaks to be 'LF' but found 'CRLF'.  linebreak-style
127:27  Error: Expected linebreaks to be 'LF' but found 'CRLF'.  linebreak-style
128:31  Error: Expected linebreaks to be 'LF' but found 'CRLF'.  linebreak-style
129:31  Error: Expected linebreaks to be 'LF' but found 'CRLF'.  linebreak-style
130:29  Error: Expected linebreaks to be 'LF' but found 'CRLF'.  linebreak-style
131:27  Error: Expected linebreaks to be 'LF' but found 'CRLF'.  linebreak-style
132:44  Error: Expected linebreaks to be 'LF' but found 'CRLF'.  linebreak-style
133:25  Error: Expected linebreaks to be 'LF' but found 'CRLF'.  linebreak-style
134:26  Error: Expected linebreaks to be 'LF' but found 'CRLF'.  linebreak-style
135:18  Error: Expected linebreaks to be 'LF' but found 'CRLF'.  linebreak-style
136:42  Error: Expected linebreaks to be 'LF' but found 'CRLF'.  linebreak-style
137:88  Error: Expected linebreaks to be 'LF' but found 'CRLF'.  linebreak-style
138:162  Error: Expected linebreaks to be 'LF' but found 'CRLF'.  linebreak-style
139:33  Error: Expected linebreaks to be 'LF' but found 'CRLF'.  linebreak-style
140:33  Error: Expected linebreaks to be 'LF' but found 'CRLF'.  linebreak-style
141:22  Error: Expected linebreaks to be 'LF' but found 'CRLF'.  linebreak-style
142:15  Error: Expected linebreaks to be 'LF' but found 'CRLF'.  linebreak-style
143:20  Error: Expected linebreaks to be 'LF' but found 'CRLF'.  linebreak-style
144:26  Error: Expected linebreaks to be 'LF' but found 'CRLF'.  linebreak-style
145:17  Error: Expected linebreaks to be 'LF' but found 'CRLF'.  linebreak-style
146:14  Error: Expected linebreaks to be 'LF' but found 'CRLF'.  linebreak-style
147:16  Error: Expected linebreaks to be 'LF' but found 'CRLF'.  linebreak-style
148:15  Error: Expected linebreaks to be 'LF' but found 'CRLF'.  linebreak-style
149:24  Error: Expected linebreaks to be 'LF' but found 'CRLF'.  linebreak-style
150:30  Error: Expected linebreaks to be 'LF' but found 'CRLF'.  linebreak-style
151:26  Error: Expected linebreaks to be 'LF' but found 'CRLF'.  linebreak-style
152:33  Error: Expected linebreaks to be 'LF' but found 'CRLF'.  linebreak-style
153:33  Error: Expected linebreaks to be 'LF' but found 'CRLF'.  linebreak-style
154:28  Error: Expected linebreaks to be 'LF' but found 'CRLF'.  linebreak-style
155:16  Error: Expected linebreaks to be 'LF' but found 'CRLF'.  linebreak-style
156:17  Error: Expected linebreaks to be 'LF' but found 'CRLF'.  linebreak-style
157:16  Error: Expected linebreaks to be 'LF' but found 'CRLF'.  linebreak-style
158:35  Error: Expected linebreaks to be 'LF' but found 'CRLF'.  linebreak-style
159:25  Error: Expected linebreaks to be 'LF' but found 'CRLF'.  linebreak-style
160:32  Error: Expected linebreaks to be 'LF' but found 'CRLF'.  linebreak-style
161:38  Error: Expected linebreaks to be 'LF' but found 'CRLF'.  linebreak-style
162:64  Error: Expected linebreaks to be 'LF' but found 'CRLF'.  linebreak-style
163:19  Error: Expected linebreaks to be 'LF' but found 'CRLF'.  linebreak-style
164:77  Error: Expected linebreaks to be 'LF' but found 'CRLF'.  linebreak-style
165:20  Error: Expected linebreaks to be 'LF' but found 'CRLF'.  linebreak-style
166:40  Error: Expected linebreaks to be 'LF' but found 'CRLF'.  linebreak-style
167:19  Error: Expected linebreaks to be 'LF' but found 'CRLF'.  linebreak-style
168:48  Error: Expected linebreaks to be 'LF' but found 'CRLF'.  linebreak-style
169:141  Error: Expected linebreaks to be 'LF' but found 'CRLF'.  linebreak-style
170:19  Error: Expected linebreaks to be 'LF' but found 'CRLF'.  linebreak-style
171:20  Error: Expected linebreaks to be 'LF' but found 'CRLF'.  linebreak-style
172:18  Error: Expected linebreaks to be 'LF' but found 'CRLF'.  linebreak-style

info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
ERROR: "build:next" exited with 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by vincethepro** [comment]
tried with npm to still broken

**Comment by AlphaNecron** [comment]
Delete the folder and clone it again on Linux. Windows is currently unsupported.

**Comment by vincethepro** [comment]
will try thank you
