### ISSUE TITLE
Installing via Docker-compose doesn't allow logins.

### ISSUE THREAD

**Issue by Chelsea-Fox** [AlphaNecron/Chakram#50]
HI, well done on this software, looks great, however I am having issues logging into the web interface.

I had followed the steps to run with compose and only thing I had changed in the config.toml was the database URL to @ localhost:5432 rather than @ postgress.

Previous to this change I would get a toast notification saying user not found for the default login.

After this change it gives an 500 error on the /api/auth/login

Any more info I need to add just ask and I can do testing on my deployment.

**Comment by AlphaNecron** [comment]
Delete the container, you **must not** alter the database url in the config file when using Docker compose, its configured automatically.

**Comment by AlphaNecron** [comment]
The `postgres` image is linked with `void` container so you don't have to change the database url unless you are deploying it manually with `node`.

**Comment by Chelsea-Fox** [comment]
Okay makes sense, thought that should have been the case.

Let me give that a shot now as last time it failed to login as the default admin:voiduser account.


**After a fresh install on a new VM, im still getting an error "User Not Found"

In the browser console I keep seeing 403 errors on the `/api/user`, and 404 errors on `/api/auth/login`


![image](https://user-images.githubusercontent.com/74470736/192714498-e2abbdfd-2bb9-4d4b-a4c9-3bd247628071.png)**

**Comment by Chelsea-Fox** [comment]
After a fresh install on a new VM, im still getting an error "User Not Found"

In the browser console I keep seeing 403 errors on the `/api/user`, and 404 errors on `/api/auth/login`

**Comment by AlphaNecron** [comment]
Can you try inspecting the database?

**Comment by Chelsea-Fox** [comment]
Apologies Im not familiar interacting with a postgres db in a docker instance, what would you say is the best way about this?

**Comment by Chelsea-Fox** [comment]
Ive managed to connect up using psql command line, ive done a `select * from information_schema.tables` to see any tables but there is no results brought back

Im thinking the migration has not applied

**Comment by AlphaNecron** [comment]
You can try using `docker exec` in the `void` container, and use `prisma studio` inside it.
Remember to `export DATABASE_URL=<the one in your config>` before executing `prisma studio` btw.

**Comment by Chelsea-Fox** [comment]
![image](https://user-images.githubusercontent.com/74470736/192728620-2ce1e85e-61e1-419a-bb3b-dd5f9f7faa39.png)

Found that the database has some tables (looks like what id think the backend DB should look like)

**Comment by Chelsea-Fox** [comment]
The only thing in the User table is the postgres db user, which i presume means the table for the default admin user has not been created?

**Comment by Chelsea-Fox** [comment]
![image](https://user-images.githubusercontent.com/74470736/192729839-4759cd82-a4d5-4133-9fd7-502c3f9d4c29.png)

Definitely looks like the default data has not been entered.

**Comment by AlphaNecron** [comment]
You can try `prisma db seed`.

**Comment by Chelsea-Fox** [comment]
Would that be from within the docker container for postgres?

**Comment by AlphaNecron** [comment]
In the `void` container.

**Comment by Chelsea-Fox** [comment]
Only way i can see to run that in the Void container is to sh into it.

when i try run `prisma db seed` it is an unknown command

**Comment by AlphaNecron** [comment]
Try prepending `yarn` or `npx` before the command?

**Comment by Chelsea-Fox** [comment]
![image](https://user-images.githubusercontent.com/74470736/192767572-44a36f1b-2273-4404-801f-878d446c02e0.png)

Trys to run however doesnt like the Database env variable.

Same thing happens with `npx`

**Comment by AlphaNecron** [comment]
You need to `export DATABASE_URL=<the one in your config>` **in the exec shell** first.

**Comment by Chelsea-Fox** [comment]
![image](https://user-images.githubusercontent.com/74470736/192768851-be800019-1794-4f8c-918c-376a466266c8.png)
After running the `export` command doesnt seem to change much at all

**Comment by Chelsea-Fox** [comment]
going to try encapsulating the url in quotes

**Comment by Chelsea-Fox** [comment]
Still a no im afraid

**Comment by AlphaNecron** [comment]
`sudo docker exec -i -t void_void_1 /bin/sh -c "DATABASE_URL=postgres://postgres:postgres@postgres/postgres yarn prisma db seed"`

**Comment by Chelsea-Fox** [comment]
Thats it now.

Thanks for your help!

might be worth adding that into the docs as I presume im not the only one that will be effected by this?

**Comment by AlphaNecron** [comment]
No need to add as it happens with `v0` only.

**Comment by Chelsea-Fox** [comment]
But if `v0` has the issue then it should be documented somewhere for just that release?

**Comment by AlphaNecron** [comment]
Sure, it will be added to the README later.
