### ISSUE TITLE
Default user not created with docker-compose

### ISSUE THREAD

**Issue by readdeo91** [AlphaNecron/Chakram#54]
I tried to deploy Void with the docker-compose way. Followed the instructions, I tried it multiple times. I tried it with the postgres container included in the docker-composeand I tried it also with my own postgresql, and it created the database tables, but the users table was empty. I always removed the containers and recreated the database between tries. Is there anything to trigger the db population?

**Comment by AlphaNecron** [comment]
You can access the internal shell and exec either `npx prisma db seed` or `yarn prisma db seed`.

**Comment by readdeo91** [comment]
Thank you. When I tried it for the first time, it didn't wotk because it coplained about the missing DATABASE_URL environment variable. This variable existed in the config.toml already, so I just added it to the environment section in the docker-compose.yaml. After this the command finished successfully and the user appeared in the databes.

**Comment by AlphaNecron** [comment]
Nice.
