### ISSUE TITLE
codes 

### ISSUE THREAD

**Issue by ryanflynn2211** [AlphaNecron/Chakram#55]
how do i make Referral code

**Comment by AlphaNecron** [comment]
Use the Discord bot.

**Comment by ryanflynn2211** [comment]
i cant i cant make a user without a reg code

**Comment by ryanflynn2211** [comment]
+ there is no command for it

**Comment by AlphaNecron** [comment]
There should be, use /wave, or you can do that within `Users` panel as an admin.

**Comment by ryanflynn2211** [comment]
there is none of those no command for /wave and no in the users panel to make a reg code

**Comment by AlphaNecron** [comment]
Are you on latest v1? You can create users within Users panel.

**Comment by ryanflynn2211** [comment]
![image](https://github.com/AlphaNecron/Void/assets/140627159/06e5c8c4-3f68-45d0-a1c2-908eaea1f81c)

**Comment by ryanflynn2211** [comment]
thats what it looks like

**Comment by AlphaNecron** [comment]
Then you may have to use some DB editors like `prisma studio` to create users manually.
