### ISSUE TITLE
help

### ISSUE THREAD

**Issue by theabysslol** [AlphaNecron/Chakram#56]
can someone help me fix how there is no make user button

**Comment by AlphaNecron** [comment]
https://github.com/AlphaNecron/Void/issues/55 You may have to use `prisma studio`.

**Comment by theabysslol** [comment]
is there not a built in user add button or invite code make or what ever

**Comment by AlphaNecron** [comment]
Currently, Void is not finished and I literally have no time to maintain this, if you want a more stable service, you can try `diced/zipline`.
