### ISSUE TITLE
Railway errors

### ISSUE THREAD

**Issue by RehanPlayz** [AlphaNecron/Chakram#9]
8:35:52 AM  ERR/SERVER  Error: listen EACCES: permission denied 0.0.0.0:80
 
Is your server listening on $PORT correctly

**Comment by RehanPlayz** [comment]
I was able to get it to work before but I deleted that project

**Comment by RehanPlayz** [comment]
![dep](https://user-images.githubusercontent.com/63925635/136172371-36c648e1-006b-49cf-9734-550fbbc250cd.png)

**Comment by AlphaNecron** [comment]
Try another port like 3000.

**Comment by RehanPlayz** [comment]
> Try another port like 3000.

I did but it's stuck on redeploying also I added a variable called PORT with the value 3000

**Comment by RehanPlayz** [comment]
Do you have a railway account so I can invite you to it

**Comment by AlphaNecron** [comment]
Wait for Railway's docker-compose support i guess?

**Comment by RehanPlayz** [comment]
> Wait for Railway's docker-compose support i guess?

I haven't tried docker compose but docker doesn't work so I made a branch with the dockerfiles removed

**Comment by RehanPlayz** [comment]
Could you accept the invite I sent

**Comment by rpxs** [comment]
docker-compose is not supported on railway. If the Dockerfile is present and you deploy, however, then it should work. Keep in mind that the Railway file system is ephemeral, meaning that your uploads will not persist between deploys.

**Comment by AlphaNecron** [comment]
Closed.
